### ISSUE TITLE
Support for the Coq programming language?

### ISSUE THREAD

**Issue by cpitclaudel** [gregsexton/origami.el#20]
Hi there,

This mode looks exciting (and much more powerful than the bundled outline).
I'm the maintainer of `company-coq`, a package for Coq/Gallina that used to do only completion, but now does a bunch more. I recently added code folding, but I had to write quite a bit of ad-hoc code for it to work nicely. The thread where the feature was discussed is https://github.com/cpitclaudel/company-coq/issues/30

I'm considering transitioning to origami for code folding. Maybe you can help with determining whether issues will arise in doing so, and if so whether they can be easily fixed?

Here are some tricky parts of the implementation:

* There are many types of delimiters:
    * `{` and `}`
    * `Module <ABC>` (or `Section <ABC>`) and `End <ABC>` (where `<ABC>` is an arbitrary name symbol)
    * `Proof.` and `Qed.` or `Defined.` or `Admitted.`
    * Bullets: these only have an opener (`+`, `*`, `-`, `++`, `**`, `--` etc.), but no closer. Calling `forward-sexp` takes you to the end of the bullet in most cases (it uses SMIE), though sometimes you have to rewind to the last match for a regexp preceeding the point that `forward-sexp` took you to.
* The bullets are clickable; clicking them toggles the corresponding block. So are braces. Ideally, so should be other openers.
* I need to be able to determine whether a point is in a folded span, and to unfold it from elisp.

Does this sound reasonable? Would Origami be a good fit? Are there things I should be aware of?

Thanks!

**Comment by gregsexton** [comment]
Origami outsources code folding to a parser that is responsible for constructing a tree of folds. You can get as complex with this as you like.

Detecting whether the point is in a fold is no problem. Manipulating the folds is also very trivial to do programatically.

The origami model looks something like this:

A parser constructs a fold tree. This tree is then compared to the previous tree and the differences are applied to the buffer. Much like how React works with a 'virtual dom'. Since we have this intermediate data structure, you can query it and manipulate it very easily without worrying about scanning through a buffer looking for overlays or whatever. 

Does this make sense? Is it helpful? Let me know how you get on. :)

**Comment by gregsexton** [comment]
Closing this as I think I answered your questions?
