### ISSUE TITLE
[question] is there a way to collpase all folds by default

### ISSUE THREAD

**Issue by ninrod** [gregsexton/origami.el#38]
I would love if, when I open a file, all folds are closed by default. is there a way to do that?

**Comment by humitos** [comment]
Yes, you can call `origami-close-all-nodes` as a hook. For example, for `python-mode` it will be something like this:

    (add-hook 'python-mode-hook (lambda () (origami-close-all-nodes (current-buffer))))

Not tested, anyway.

**Comment by ninrod** [comment]
Ok, that works! thank you @humitos

**Comment by cryptomaniac512** [comment]
Sorry, but that not working for me
```(add-hook 'prog-mode-hook (lambda ()  (origami-close-all-nodes (current-buffer))))```
What am I doing wrong? :(

**Comment by ninrod** [comment]
@cryptomaniac512, this is working for me:

```elisp
(use-package origami :ensure t
  :config 
    (add-hook 'prog-mode-hook 
      (lambda () 
        (setq-local origami-fold-style 'triple-braces)
        (origami-mode)
        (origami-close-all-nodes (current-buffer)))))
```

**Comment by cryptomaniac512** [comment]
@ninrod thank you!

**Comment by logangrado** [comment]
Hi - I'm also having trouble with this. I'm trying to:
1. Ensure origami-mode is activated any time a code editing mode is activated, and
2. Run `origami-close-all-nodes` when origami-mode starts.

the problem is, I can't get both to work.


Here's the relevant section of my `use-package.el`
```
(use-package origami
  :ensure t
  :init
  (dolist (mode code-editing-mode-hooks)
    (add-hook mode 'origami-mode))  
  :config
  (add-hook 'origami-mode-hook
            (lambda ()
              (origami-close-all-nodes (current-buffer))))
  )
```

And the definition of `code-editing-mode-hooks`:
```
(defvar code-editing-mode-hooks '(c-mode-common-hook
                                  ...
                                  python-mode-hook
                                  yaml-mode-hook))
```

The problem is I get `File mode specification error: (error Lisp nesting exceeds 'max-lisp-eval-depth')`. If I remove the `:config` section, then I get origami mode enabled by default like I want. If I remove the `:init` section, then I get origami mode to close all nodes when I enable it with `M-x origami-mode`, but I can't seem to get both.

Obviously, this seems to be some sort of recursion error. I've also tried replacing the `:config` section with 
```
  (lambda() (interactive) (call-interactively 'origami-close-all-nodes))

```
which no longer throws an error, but does not fold code on startup.

Can you help?
