### ISSUE TITLE
origami-toggle-node cannot toogle at the beginning of the node

### ISSUE THREAD

**Issue by c02y** [gregsexton/origami.el#42]
Fox example:

```
>int main()
{
......
}
```

the point is at beginning of the "int main" line, the ">" position (or any position before the symbol "{"), executing origami-toggle-node will do nothing, but expected to toggle the whole function, it only works inside the function (inside the "{...}").  But origami-recursively-toggle-node or origami-toggle-all-nodes work as expected. even from the beginning of the node.

BTW: origami-toggle-node works at the beginning of a defun line in elisp file.

**Comment by ninrod** [comment]
+1. @gregsexton!

Here's a screenshot to demonstrate: 

point is above the `z` in zsh. I cannot open or close the fold in this position. I have to place point somewhere inside the braces on that line so that origami can open and close folds for me. 

Being able to open or close a fold anywhere in a line that contains a fold would be a significant comfort improvement.

<img width="623" alt="screen shot 2016-10-17 at 10 15 06" src="https://cloud.githubusercontent.com/assets/8352747/19437113/a0049b3c-9452-11e6-9087-2a96d86b4074.png">

**Comment by ninrod** [comment]
In my specific use case, I think the way to go would be to change the regex listed [here](https://github.com/gregsexton/origami.el/blob/master/origami-parsers.el#L258). Makes sense?

**Comment by jojojames** [comment]
+1 I don't think any other folding packages support this behavior.

I like how vim does its folding.

**Comment by ninrod** [comment]
you can construct a custom function with `save-excursion`. like [here](https://github.com/ninrod/dotfiles/blob/master/emacs/boot.org#ninrodorigami-toggle-node).

**Comment by jojojames** [comment]
@ninrod That's a good head start.

```
        public void FunctionName([Variable one)
        {
```

I'll probably have to tweak it to do a 'lookahead' for 1 or 2 lines before giving up and going upwards up the stack.

**Comment by ninrod** [comment]
@jojojames yes that's the spirit.

**Comment by jojojames** [comment]
@ninrod 
Here's a quick slathering, if I have time, I'll try to improve it more. Would also appreciate anyone taking and running with it to improve the folding experience.

Uses s.el for the string parsing.

```
  (defun jojo/origami-toggle-node ()
    (interactive)
    (if (not (member major-mode
                     '(c-mode
                       java-mode csharp-mode c++-mode js-mode
                       js2-mode php-mode json-mode ruby-mode
                       motion-mode swift-mode css-mode)))
        (call-interactively #'origami-toggle-node)
      (cond
       ((s-ends-with? "{" (s-trim (thing-at-point 'line t)))
        (save-excursion
          (goto-char (point-at-eol))
          (call-interactively #'origami-toggle-node)))
       ((save-excursion
          (forward-line 1)
          (when (s-starts-with? "{" (s-trim (thing-at-point 'line t)))
            (goto-char (point-at-eol))
            (call-interactively #'origami-toggle-node)
            t))
        t)
       (t
        (call-interactively #'origami-toggle-node)))))
```

**Comment by ninrod** [comment]
@jojojames, I only use vim's  ```#{{{ #}}}``` triple bracket style folding, but your example looks promising.

**Comment by gregsexton** [comment]
The behaviour of origami-toggle-node you describe is by design. You should use origami-forward-toggle-node. IIRC, this won't work across lines though - again this is by design so as not to be surprising. 

You should be able to easily compose origami-forward-fold (jumps to the next folding point) and origami-toggle-node to get the behaviour you want. No need to parse the buffer.

**Comment by ninrod** [comment]
by the way thank you for the awesome package @gregsexton!
